name: "CI"

on:
  pull_request:
  push:
    branches:
      - "master"

env:
  CI: true
  TZ: 'Europe/Paris'

jobs:
  run:
    name: "PHPUnit (PHP 7.4)"
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          ini-values: date.timezone=${{ env.TZ }}

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v1"

      - name: CS Fixer
        run: php vendor/bin/php-cs-fixer fix --dry-run

      - name: Prepare
        run: cp init_db.yml.dist init_db.yml

      - name: Run PHPUnit
        run: php vendor/bin/simple-phpunit -v

      - name: Analyse
        run: php vendor/bin/phpstan analyse
